@extends('layouts.app')

@section('title', 'Create Invoice')

@section('content')
<h2>CREATE INVOICE</h2>
<hr>
<form action="{{ route('invoices.store') }}" method="POST">
    @csrf
    <div class="row mb-3">
        <div class="col-md-4">
            <label for="invoice_number" class="form-label">Invoice No</label>
            <input type="text" class="form-control" id="invoice_number" name="invoice_number" value="{{ $invoiceNumber }}" readonly>
            <small class="form-text text-muted">Auto generated by system</small>
        </div>
        <div class="col-md-4">
            <label for="customer_name" class="form-label">Customer Name</label>
            <input type="text" class="form-control @error('customer_name') is-invalid @enderror" id="customer_name" name="customer_name" value="{{ old('customer_name') }}" placeholder="Input nama customer" required>
            @error('customer_name') <div class="invalid-feedback">{{ $message }}</div> @enderror
        </div>
        <div class="col-md-4">
            <label for="delivery_date" class="form-label">Delivery Date</label>
            <input type="date" class="form-control @error('delivery_date') is-invalid @enderror" id="delivery_date" name="delivery_date" value="{{ old('delivery_date', date('Y-m-d')) }}" placeholder="Input delivery date" required>
             @error('delivery_date') <div class="invalid-feedback">{{ $message }}</div> @enderror
        </div>
    </div>

    <h4>Detail Invoice</h4>
    <table class="table table-bordered" id="invoiceDetailsTable">
        <thead>
            <tr>
                <th>Coil Number</th>
                <th>Width (mm)</th>
                <th>Length (mm)</th>
                <th>Thickness (mm)</th>
                <th>Weight (kg)</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {{-- Baris detail akan ditambahkan oleh JavaScript --}}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" class="text-end fw-bold">Total Price</td>
                <td id="totalPriceDisplay" class="fw-bold">0.00</td>
                <td></td>
            </tr>
        </tfoot>
    </table>
    <button type="button" class="btn btn-primary mb-3" id="addLineBtn">Add Line</button>
    <small class="form-text text-muted d-block mb-3">Untuk menambahkan baris baru pada detail invoice.</small>
    <small class="form-text text-muted d-block mb-3">Kalkulasi otomatis ketika Price pada detail invoice diinputkan.</small>


    <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</form>
@endsection

@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const addLineBtn = document.getElementById('addLineBtn');
        const detailsTableBody = document.querySelector('#invoiceDetailsTable tbody');
        const totalPriceDisplay = document.getElementById('totalPriceDisplay');
        let detailIndex = 0;

        function addDetailRow() {
            const newRow = detailsTableBody.insertRow();
            newRow.innerHTML = `
                <td><input type="text" name="details[${detailIndex}][coil_number]" class="form-control form-control-sm" required></td>
                <td><input type="number" name="details[${detailIndex}][width]" class="form-control form-control-sm detail-calc" step="0.01" min="0" required></td>
                <td><input type="number" name="details[${detailIndex}][length]" class="form-control form-control-sm detail-calc" step="0.01" min="0" required></td>
                <td><input type="number" name="details[${detailIndex}][thickness]" class="form-control form-control-sm detail-calc" step="0.01" min="0" required></td>
                <td><input type="number" name="details[${detailIndex}][weight]" class="form-control form-control-sm detail-calc" step="0.01" min="0" required></td>
                <td><input type="number" name="details[${detailIndex}][price]" class="form-control form-control-sm detail-price" step="0.01" min="0" required></td>
                <td><button type="button" class="btn btn-danger btn-sm remove-line-btn">Remove</button></td>
            `;
            detailIndex++;
            attachEventListenersToRow(newRow);
        }

        function attachEventListenersToRow(row) {
            row.querySelector('.remove-line-btn').addEventListener('click', function() {
                row.remove();
                updateTotalPrice();
            });
            row.querySelectorAll('.detail-price').forEach(input => {
                input.addEventListener('input', updateTotalPrice);
            });
        }

        function updateTotalPrice() {
            let total = 0;
            document.querySelectorAll('#invoiceDetailsTable tbody .detail-price').forEach(input => {
                const price = parseFloat(input.value) || 0;
                total += price;
            });
            totalPriceDisplay.textContent = total.toFixed(2);
        }

        addLineBtn.addEventListener('click', addDetailRow);

        // Tambah baris pertama secara otomatis jika belum ada data lama (misal dari validasi error)
        @if(!old('details'))
            addDetailRow();
        @else
            // Jika ada old data (karena validation error), render ulang baris tersebut
            @foreach(old('details', []) as $key => $detail)
                const existingRow = detailsTableBody.insertRow();
                existingRow.innerHTML = `
                    <td><input type="text" name="details[${key}][coil_number]" value="{{ $detail['coil_number'] ?? '' }}" class="form-control form-control-sm" required></td>
                    <td><input type="number" name="details[${key}][width]" value="{{ $detail['width'] ?? '' }}" class="form-control form-control-sm detail-calc" step="0.01" min="0" required></td>
                    <td><input type="number" name="details[${key}][length]" value="{{ $detail['length'] ?? '' }}" class="form-control form-control-sm detail-calc" step="0.01" min="0" required></td>
                    <td><input type="number" name="details[${key}][thickness]" value="{{ $detail['thickness'] ?? '' }}" class="form-control form-control-sm detail-calc" step="0.01" min="0" required></td>
                    <td><input type="number" name="details[${key}][weight]" value="{{ $detail['weight'] ?? '' }}" class="form-control form-control-sm detail-calc" step="0.01" min="0" required></td>
                    <td><input type="number" name="details[${key}][price]" value="{{ $detail['price'] ?? '' }}" class="form-control form-control-sm detail-price" step="0.01" min="0" required></td>
                    <td><button type="button" class="btn btn-danger btn-sm remove-line-btn">Remove</button></td>
                `;
                attachEventListenersToRow(existingRow);
                detailIndex = Math.max(detailIndex, {{ $key }} + 1);
            @endforeach
            updateTotalPrice(); // Hitung ulang total jika ada data lama
        @endif
    });
</script>
@endpush